### PR TITLE
Freestyle training 5

### PR DESCRIPTION
**Pull request by unfazedEgnimadevspace**
Feat- 2nd part of the free style training feature, Users can the select a particular exercise from the index page and get 
redirected to training new path where they can create new training objects based on the exercise they have chosen.

Hello @americodls 

I have split the large PR into two PRs freestyle_training_4 and freestyle_training_5 , if there any changes you would love to make or a different approach to the feature i would love to hear from you.

### CODE REVIEW

**Review by americodls — COMMENTED** [review]
I can see a bunch of repetition from other PR here.

Maybe the base branch for this PR is not `main`, it is the branch of the other PR.

You can change that doing this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by unfazedEgnimadevspace** [comment]
I just checked and it's the main branch, i think it is because we have not merged the first part of the feature to the main branch that is why changes made in the freestyle_training_4 pull request are spilling here . i need the changes made there so as to make the changes made here to work cause it's one feature. I don't know if there is any way i can go around that

Thanks

**Comment by unfazedEgnimadevspace** [comment]
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.05.23-23_59_55.webm](https://github.com/unfazedEgnimadevspace/Gracker/assets/96634477/7979d819-9c37-4d47-940e-631c84ddda02)

This is the video of the full feature

Thanks

**Comment by unfazedEgnimadevspace** [comment]
screenshot-1
screenshot-2
screenshot-3
These are the mobile views

**Comment by americodls** [comment]
That looks very good! I didn't test it but I loved the video and screenshots.
Let's focus more on mobile, that's how we will use it!

I'm really looking forward to using this app!

You can merge it. We can fix small things later.

**Pull request merged**
