### PR TITLE
Feat- Designed the ui for the login and signup pages

### PR DESCRIPTION
**Pull request by unfazedEgnimadevspace**

### CODE REVIEW

**Comment by americodls** [comment]
A good and common practice in PRs is adding a description that states your reasoning on your change and when UI is modified also is a good thing adding "before" and "after" screenshots.

That will help reviewers to evaluate easily what is the result of your work.

Can you add those screenshots here?

**Comment by unfazedEgnimadevspace** [comment]
before-signup
After image
login-before
after -login


These are the screenshots of the signup before and after and the login before and after 

Thank you for the tip

**Comment by americodls** [comment]
Wooow!!! This looks amazing!!! 🤩

Super improvement on UI here!

As far as I can see we certainly better merging this!

**Review by americodls — APPROVED** [review]
🥇

**Pull request merged**
