### PR TITLE
Freestyle training 3

### PR DESCRIPTION
**Pull request by unfazedEgnimadevspace**
Hello @americodls 

I am 90% done with the freestyle training feature. 

This is the workflow of the feature 

1 User clicks the freestyle training link from the home page 
2 They get redirected to index page of the freestyle_training controller 
3 On the index page users can choose what part of the body they want to work out on.
4 I wrote a private method apply_filter to filter the exercises data and fetch exercises with that particular body part 
5 users get redirected to filter_page.html.erb where all the exercises with that body part are displayed and paginated 
6 Users can select a particular exercise from the displayed exercises ,  they get redirected to the show page where they can create trainings from that particular exercise.

This is the workflow of the feature i just created,  if there are any changes or corrections you would love to make to the code i would love to hear them, or we can discuss them as well in the meeting 

Thank you once again for your time

### CODE REVIEW

**Review by americodls — COMMENTED** [review]
To be honest I didn't check everything.
This PR is too large.
Probably your would get the same feedback you are getting from me.

Try to split this PR into multiple PRs where each PR solves only one specific problem.

It is hard and tiring to review large PRs with multiple purposes. We can avoid that.

**Comment by unfazedEgnimadevspace** [comment]
Hello @americodls 

I am sorry for the large pull request, i thought as much as well it won't happen again... I wanted us to review everything at once in the meeting but i guess i made a mistake.  I would split them up and have it ready for you tomorrow.

Thank you

**Comment by unfazedEgnimadevspace** [comment]
I understand, I don't feel bad just a little disappointed with myself.

Thank you so much americo for your time, I am really learning alot and don't hold back for any reviews you want to make🙏

**Comment by americodls** [comment]
It seems this PR can be closed as well, right?
Or there is any remaining feature you want to extract from here?
If not, let's close it.

**Pull request closed without merging**
